# - type: job
#   id: LPPCentralCommandRepresentative
#   name: job-name-centcom-representative
#   description: job-description-representative
#   playTimeTracker: JobCentralCommandRepresentative
#   requirements:
#    - !type:CharacterDepartmentTimeRequirement
#      department: Command
#      min: 108000
#    - !type:CharacterPlaytimeRequirement
#      tracker: JobCaptain
#      min: 54000
#   setPreference: false
#   startingGear: LPPCentcomRepresentativeGear
#   icon: "JobIconNanotrasen"
#   supervisors: job-supervisors-centcom
#   canBeAntag: false
#   accessGroups:
#   - AllAccess
#   special:
#   - !type:AddImplantSpecial
#     implants: [ TrackingImplant, MindShieldImplant ]

# - type: startingGear
#   id: LPPCentcomRepresentativeGear
#   equipment:
#     jumpsuit: ClothingUniformJumpsuitCentcomOfficer
#     back: ClothingBackpackHOPFilled
#     shoes: ClothingShoesBootsLaceup
#     eyes: ClothingEyesGlassesSunglasses
#     gloves: ClothingHandsGlovesColorGray
#     outerClothing: ClothingOuterVest
#     id: LPPCentralCommandRepresentativePDA
#     ears: ClothingHeadsetCentCom
#     belt: BoxFolderClipboard
#     pocket1: Paper
#     pocket2: TrackingImplanter
#     socks: LPPClothingUnderSocksNormGreen
#     underwear: LPPBoxerGreen
#   underwear: LPPBriefsGreen
#   breast: LPPBraAltGreen
#   satchel: ClothingBackpackSatchelHOPFilled
#   duffelbag: ClothingBackpackDuffelHOPFilled

# - type: entity
#   parent: BasePDA
#   id: LPPCentralCommandRepresentativePDA
#   name: centcom representative PDA
#   description: Centcom representative PDA.
#   components:
#   - type: Pda
#     id: LPPCentralCommandRepresentativeIDCard
#     state: pda-centcom
#     penSlot:
#       startingItem: PenCentcom
#       whitelist:
#         tags:
#         - Write
#   - type: PdaBorderColor
#     borderColor: "#32CD32"
#   - type: Icon
#     state: pda-centcom

# - type: entity
#   parent: IDCardStandard
#   id: LPPCentralCommandRepresentativeIDCard
#   name: centcom representative ID card
#   description: Centcom representative ID card.
#   components:
#   - type: Sprite
#     layers:
#     - state: gold
#     - state: idcentcom
#   - type: Item
#     heldPrefix: gold
#   - type: PresetIdCard
#     job: LPPCentralCommandRepresentative
#   - type: Access
#     groups:
#     - AllAccess

# - type: entity
#   id: LPPSpawnCentralCommandRepresentative
#   parent: SpawnPointJobBase
#   name: central command representative spawn
#   components:
#     - type: SpawnPoint
#       job_id: LPPCentralCommandRepresentative
#     - type: Sprite
#       layers:
#         - state: green
#         - state: centcom
